// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_lbuE4oYYJyTs2Zz6x0r_xzVWSVy335o',
    appId: '1:972603944599:web:00832b47b5d70bedc983d2',
    messagingSenderId: '972603944599',
    projectId: 'unravel-340708',
    authDomain: 'unravel-340708.firebaseapp.com',
    storageBucket: 'unravel-340708.appspot.com',
    measurementId: 'G-80MTNWG0EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuhlr0PzfuACU-02OLYgYqc9Wlyl7wkxM',
    appId: '1:972603944599:android:498e34a85b2a9f2cc983d2',
    messagingSenderId: '972603944599',
    projectId: 'unravel-340708',
    storageBucket: 'unravel-340708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBXvYX3PaCkmO5XJi8mSn6sApo_O-0llc',
    appId: '1:972603944599:ios:90b06c43d40d8ec7c983d2',
    messagingSenderId: '972603944599',
    projectId: 'unravel-340708',
    storageBucket: 'unravel-340708.appspot.com',
    iosBundleId: 'com.example.nirvana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBXvYX3PaCkmO5XJi8mSn6sApo_O-0llc',
    appId: '1:972603944599:ios:e1d801f82f96622cc983d2',
    messagingSenderId: '972603944599',
    projectId: 'unravel-340708',
    storageBucket: 'unravel-340708.appspot.com',
    iosBundleId: 'com.example.nirvana.RunnerTests',
  );
}
